language: python
python:
    - "2.7"
service:
    - mysql
before_script:
    - mysql -e 'create database test;'
install:
    - "pip install -r requirements.txt"
    - "pip install tox"
    - "pip install -r test/requirements.txt"
script:
    - flake8
    - nosetests -c nosetests.ini
    - tox
notifications:
    email:
        recipients:
            - leannmak@139.com
        on_success: always
        on_failure: always

branches:
    only:
        - master
        - develop

after_success:
    - coveralls